spring:
  application:
    name: license-service
  config:
    import: optional:configserver:http://localhost:8071

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8070/eureka/
    instance:
      prefer-ip: true



